export default {
  MIN: 1,
  MAX: 9,
  TOTAL_QUESTIONS: 5,
  ENTER: 'ENTER',
  CLEAR: 'CLEAR',
  BACKSPACE: 'BACKSPACE',
  INVISIBLE: 'invisible',
  FOCUSED: 'focused',
  STATUS_SUCCESS : 'status-success',
  STATUS_FAIL : 'status-fail',
  MULTIPLY_CODE: '&#10005;',
  CLEAR_CODE: '&#10005;',
  ENTER_CODE: '&#10132;',
  BACK_CODE: '&#8634;',
  TAB_CODE: '&#x2630;',
  REVERSE_CODE: '&#8645;',
  SHARE_CODE: '&#10148;',
  INSERT_CODE: '&#x270E;',
  MGH_MULTIPLY: 'mgh_multiply',
  ZERO_TIME: '0.00'
}